
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.math.utility;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-11-06T18:54:26.307Z
 * Generated source version: 3.6.2
 *
 */

@javax.jws.WebService(
                      serviceName = "MathUtilityService",
                      portName = "MathUtilityPort",
                      targetNamespace = "http://utility.math.com/",
                      wsdlLocation = "http://127.0.0.1:8080/MathUtility/services/MathUtilityPort?wsdl",
                      endpointInterface = "com.math.utility.MathUtility")

public class MathUtilityPortImpl implements MathUtility {

    private static final Logger LOG = Logger.getLogger(MathUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.math.utility.MathUtility#factorial(int arg0)*
     */
    public int factorial(int arg0) {
        LOG.info("Executing operation factorial");
        System.out.println(arg0);
        try {
            int _return = 388945185;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.math.utility.MathUtility#addIntegers(int arg0, int arg1)*
     */
    public int addIntegers(int arg0, int arg1) {
        LOG.info("Executing operation addIntegers");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 1118417303;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
