
package default_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-11-06T19:41:25.121Z
 * Generated source version: 3.6.2
 *
 */
public final class MathUtility_MathUtilityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://utility.math.com/", "MathUtilityService");

    private MathUtility_MathUtilityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MathUtilityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MathUtilityService ss = new MathUtilityService(wsdlURL, SERVICE_NAME);
        MathUtility port = ss.getMathUtilityPort();

        {
        System.out.println("Invoking factorial...");
        int _factorial_arg0 = 829403498;
        int _factorial__return = port.factorial(_factorial_arg0);
        System.out.println("factorial.result=" + _factorial__return);


        }
        {
        System.out.println("Invoking addIntegers...");
        int _addIntegers_arg0 = -689395479;
        int _addIntegers_arg1 = 254018852;
        int _addIntegers__return = port.addIntegers(_addIntegers_arg0, _addIntegers_arg1);
        System.out.println("addIntegers.result=" + _addIntegers__return);


        }

        System.exit(0);
    }

}
