
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-11-06T19:41:25.362Z
 * Generated source version: 3.6.2
 *
 */

@javax.jws.WebService(
                      serviceName = "MathUtilityService",
                      portName = "MathUtilityPort",
                      targetNamespace = "http://utility.math.com/",
                      wsdlLocation = "http://127.0.0.1:8080/MathUtilityWithRMI/services/MathUtilityPort?wsdl",
                      endpointInterface = "default_package.MathUtility")

public class MathUtilityPortImpl implements MathUtility {

    private static final Logger LOG = Logger.getLogger(MathUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.MathUtility#factorial(int arg0)*
     */
    public int factorial(int arg0) {
        LOG.info("Executing operation factorial");
        System.out.println(arg0);
        try {
            int _return = 925261645;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#addIntegers(int arg0, int arg1)*
     */
    public int addIntegers(int arg0, int arg1) {
        LOG.info("Executing operation addIntegers");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 1954608451;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
