package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-11-06T19:41:25.429Z
 * Generated source version: 3.6.2
 *
 */
@WebService(targetNamespace = "http://utility.math.com/", name = "MathUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface MathUtility {

    @WebMethod
    @RequestWrapper(localName = "factorial", targetNamespace = "http://utility.math.com/", className = "default_package.Factorial")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://utility.math.com/", className = "default_package.FactorialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int factorial(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addIntegers", targetNamespace = "http://utility.math.com/", className = "default_package.AddIntegers")
    @ResponseWrapper(localName = "addIntegersResponse", targetNamespace = "http://utility.math.com/", className = "default_package.AddIntegersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addIntegers(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
